// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpDpDA_YV5s67DTqc75KE1IrF2Uv0Bw8',
    appId: '1:468801411897:web:776b9ae55b38fd09a7a6e8',
    messagingSenderId: '468801411897',
    projectId: 'careonew-ebd63',
    authDomain: 'careonew-ebd63.firebaseapp.com',
    storageBucket: 'careonew-ebd63.firebasestorage.app',
    measurementId: 'G-3VTF1EVLS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK11Fqizb6VysX8jYm0p1zwXOwJnitP4s',
    appId: '1:468801411897:android:d547de9cbd20a326a7a6e8',
    messagingSenderId: '468801411897',
    projectId: 'careonew-ebd63',
    storageBucket: 'careonew-ebd63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_w044fDSlxb1n7xbfXQeRrJHv10bttE',
    appId: '1:468801411897:ios:62512e0036bb2f33a7a6e8',
    messagingSenderId: '468801411897',
    projectId: 'careonew-ebd63',
    storageBucket: 'careonew-ebd63.firebasestorage.app',
    iosBundleId: 'com.example.careoNew1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_w044fDSlxb1n7xbfXQeRrJHv10bttE',
    appId: '1:468801411897:ios:62512e0036bb2f33a7a6e8',
    messagingSenderId: '468801411897',
    projectId: 'careonew-ebd63',
    storageBucket: 'careonew-ebd63.firebasestorage.app',
    iosBundleId: 'com.example.careoNew1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwpDpDA_YV5s67DTqc75KE1IrF2Uv0Bw8',
    appId: '1:468801411897:web:1d5c6e1b58c6d980a7a6e8',
    messagingSenderId: '468801411897',
    projectId: 'careonew-ebd63',
    authDomain: 'careonew-ebd63.firebaseapp.com',
    storageBucket: 'careonew-ebd63.firebasestorage.app',
    measurementId: 'G-RTD90C9GDD',
  );
}
